# Generated by Django 5.2.2 on 2025-06-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_session_alter_service_title_sessionday'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_app.session'),
        ),
    ]
