# Generated by Django 5.2.2 on 2025-06-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_timeline_timeslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionDay',
            new_name='ServiceDay',
        ),
        migrations.RenameModel(
            old_name='Session',
            new_name='ServiceTimeline',
        ),
    ]
