# Generated by Django 5.2.2 on 2025-06-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_app.session'),
        ),
    ]
