# Generated by Django 5.2.2 on 2025-06-08 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_timeslot_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='session',
        ),
        migrations.AddField(
            model_name='servicetimeline',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_app.service'),
            preserve_default=False,
        ),
    ]
