# Generated by Django 5.2.2 on 2025-06-10 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_remove_service_session_servicetimeline_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetimeline',
            name='service',
        ),
        migrations.RemoveField(
            model_name='session',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='session',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='time_line',
        ),
        migrations.AddField(
            model_name='service',
            name='session_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='session_hour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='work_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_app.appointment'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book_app.service'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ServiceDay',
        ),
        migrations.DeleteModel(
            name='ServiceTimeline',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
