# Generated by Django 5.2.2 on 2025-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0012_remove_servicetimeline_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='session_hour',
            field=models.FloatField(),
        ),
    ]
