# Generated by Django 5.2.2 on 2025-06-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_alter_service_session_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='book_app.service'),
        ),
    ]
